### ISSUE TITLE
Declare SystemRequirements

### ISSUE THREAD

**Issue by krlmlr** [eweine/qqconf#19]
It seems that the fftw3 library is required for the most recent CRAN version. IIUC, declaring it in SystemRequirements will help sysreqdb pick it up: https://github.com/r-hub/sysreqsdb/issues/92#issuecomment-1069655724.

**Comment by eweine** [comment]
Hey @krlmlr, thanks for pointing this out! I believe this PR will fix the issue. You should be able to pull the development version and test, and we will push the fix to CRAN asap.

Eric.
