### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Ljie03** [eweine/qqconf#28]
Hello, I am a user of centos7 and I am reporting the following error after installing using the command in R.
```
install.packages('qqconf')
```
```
jointlevel_fft_twosided.cpp:10:10: fatal error: fftw3.h: 没有那个文件或目录
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.
make: *** [jointlevel_fft_twosided.o] 错误 1
ERROR: compilation failed for package ‘qqconf’
* removing ‘/home/me/R/x86_64-pc-linux-gnu-library/4.1/qqconf’
Warning in install.packages :
  installation of package ‘qqconf’ had non-zero exit status
```
My fftw=3.3.3

Looking forward to your reply, thank you!

**Comment by eweine** [comment]
Hello,

Are you sure that your path is configured correctly so that gcc can pick up your installed libraries? Could you perhaps try creating a c++ file that includes fftw3.h and try running it with gcc?

**Comment by conniecl** [comment]
Hi, I face the same question, and after install the fftw3, the above question was solved, but facing the "undefined symbol: fftw_execute" problem, the details are below. Hope can get your help. My system is "Ubuntu 18.04.3 LTS (GNU/Linux 5.4.0-100-generic x86_64)".
```
Error: package or namespace load failed for ‘qqconf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/hello/lchen/software/anaconda3/envs/survey/lib/R/library/00LOCK-qqconf/00new/qqconf/libs/qqconf.so':
  /home/hello/lchen/software/anaconda3/envs/survey/lib/R/library/00LOCK-qqconf/00new/qqconf/libs/qqconf.so: undefined symbol: fftw_execute
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/hello/lchen/software/anaconda3/envs/survey/lib/R/library/qqconf’

The downloaded source packages are in
	‘/tmp/Rtmp7fWPD0/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("qqconf") :
  installation of package ‘qqconf’ had non-zero exit status
```

**Comment by conniecl** [comment]
And my fftw = 3.3.8

**Comment by eweine** [comment]
Hey there,

This looks like a linking issue to me. 

qqconf links to the fftw3 library by linking to a library in `/usr/local/lib` as follows:

```
PKG_LIBS=-L/usr/local/lib -lfftw3
```

I'm guessing that fftw3 is not installed in that library for you. If I cd into that directory on my local machine, I see two files, `libfftw3.a` and `libfftw3.la` that provide the linking information. 

So, I think that the easiest option would be to modify [the makevars file](https://github.com/eweine/qqconf/blob/master/qqconf/src/Makevars) to point to where fftw3 has put the files on your local machine. Alternatively, you could configure your machine to put the library linking files in `/usr/local/lib`.

Please let me know if this helps,

Eric.
